SKFP-284 converting FHIR resources into Avro files stored on S3
kids-first/kf-etl-clin-portal pull request #1
Opened 2021-11-16 19:36 UTC by joelplourde3

- Keycloak configuration is non-existent at the moment, its just a basic cookie which has to be manually refreshed
- Most of the PR is just schemas, the code is near the bottom.

2021-11-18 14:37 UTC, jecos requested changes

2021-11-18 14:37 UTC, jecos commented on fhavro-export/src/main/scala/bio/ferlab/fhir/etl/task/FhavroBulkExporter.scala
> +      .filter(!_.isBlank)
Combien the 2 first map togetehres and deconstruct the tuple. Tip map.map.flatMap.filter could be done also with a foldLeft

2021-11-18 14:37 UTC, jecos commented on fhavro-export/src/main/scala/bio/ferlab/fhir/etl/task/FhavroBulkExporter.scala
> +    }).asJava
My preference would be to convert to Java at the last moment

2021-11-18 14:37 UTC, jecos commented on fhavro-export/src/main/scala/bio/ferlab/fhir/etl/task/FhavroBulkExporter.scala
> +    print(s"[main] INFO ${getClass.getName} - %s%% ${verb}ed.\r".format((progress.incrementAndGet().floatValue() / total) * 100))
use logger instead

2021-11-18 14:49 UTC, joelplourde3 commented on fhavro-export/src/main/scala/bio/ferlab/fhir/etl/task/FhavroBulkExporter.scala
> +    print(s"[main] INFO ${getClass.getName} - %s%% ${verb}ed.\r".format((progress.incrementAndGet().floatValue() / total) * 100))
Logger unfortunately does not support the \r where the progress as a % is displayed in a single line (to avoid blowing up the log file).

- 50.1% <-- Update on a single line

- 50.1% <-- New line every update
- 50.2%
- ...

The result is less convoluted log file when debugging

2021-11-18 15:01 UTC, joelplourde3 commented on fhavro-export/src/main/scala/bio/ferlab/fhir/etl/task/FhavroBulkExporter.scala
> +    }).asJava
Any particular reason why? Maybe improve readability ?

2021-11-18 16:34 UTC, joelplourde3 commented
Need to investigate some issue related to crashing the FHIR server EVERYTIME this ETL runs hahahah

2021-11-19 17:12 UTC, joelplourde3 commented
All good, removed all bulk export functionality (moved it to a different branch), this is all sync. Will work on adding tests

2022-01-07 14:21 UTC, merged