:sparkles: Add exp strategy aggregate in study index
kids-first/kf-etl-clin-portal pull request #171
Opened 2023-03-29 23:32 UTC by evans-g-crsj

2023-03-29 23:33 UTC, evans-g-crsj commented on JenkinsfileRunKfEtl
According to Meen, at this time, we have to use FHIR QA. I added all the studies I could found.

2023-03-29 23:58 UTC, jecos requested changes

2023-03-29 23:58 UTC, jecos commented on prepare-index/src/test/scala/model/SEQUENCING_EXPERIMENT.scala
> +case class SEQUENCING_EXPERIMENT_ROW_PARTITIONED_BY_STUDY(study_id: String = "SD_Z6MWD3H0", experiment_strategy: String = "WGS")
you should reuse SEQUENCING_EXPERIMENT object

2023-03-29 23:58 UTC, jecos commented on prepare-index/src/main/scala/bio/ferlab/fhir/etl/centricTypes/StudyCentric.scala
> -        collect_set(col("experiment_strategy")) as "experimental_strategy",
I know this is my suggestion to remove this field, but maybe we should also collect this. Let discuss togetheer

2023-03-30 00:25 UTC, jecos approved these changes

2023-03-30 00:33 UTC, merged