feat: SKFP-793 support files with only INFO_CSQ and use INFO_CSQ instead of INFO_ANN when both are present
kids-first/kf-etl-clin-portal pull request #316
Opened 2024-02-09 21:36 UTC by celinepelletier

We have 3 scenarios: 

- file only have INFO_ANN
- file only have INFO_CSQ
- file have both INFO_ANN and INFO_CSQ

to avoid to change all the code of the ETL, I just rename the column INFO_CSQ > INFO_ANN and use it first if both exist

2024-02-09 21:44 UTC, laurabegin requested changes

2024-02-09 21:44 UTC, laurabegin commented on etl/src/main/scala/bio/ferlab/etl/normalized/genomic/KFVCFUtils.scala
> +      }
Préférable d'utilser une val. Tu peux faire de quoi du genre à la place : 
```scala
val df = vcf(files.toList, referenceGenomePath)
val renamedDf =  if (df.columns.contains("INFO_ANN") && df.columns.contains("INFO_CSQ")) {
        df.withColumnRenamed("INFO_ANN", "OLD_INFO_ANN")
      } else if (!df.columns.contains("INFO_ANN")) {
        df.withColumnRenamed("INFO_CSQ", "INFO_ANN")
      }

```

2024-02-13 14:16 UTC, laurabegin approved these changes

2024-02-13 17:58 UTC, jecos approved these changes

2024-02-13 17:58 UTC, merged